// src/lib/components/editors/ChecklistEditor.svelte
<!-- src/lib/components/editors/ChecklistEditor.svelte -->
<script lang="ts">
  import { createEventDispatcher, onMount, tick } from 'svelte';
  import type { ChecklistItem } from '$lib/types';
  import SortableChecklist from './SortableChecklist.svelte';
  
  export let checklistData: ChecklistItem[] = [];
  
  const dispatch = createEventDispatcher<{
    dataChange: ChecklistItem[];
  }>();
  
  let items: ChecklistItem[] = [];
  let isMobile = false;
  
  // Initialize from props - ensure at least one empty item
  $: if (checklistData.length === 0) {
    items = [{ text: '', checked: false }];
  } else {
    items = [...checklistData];
  }
  
  // Progress calculation
  $: completedCount = items.filter(item => item.checked && item.text.trim()).length;
  $: totalCount = items.filter(item => item.text.trim()).length;
  $: progressPercentage = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  
  // Mobile detection
  onMount(() => {
    const checkMobile = () => {
      isMobile = window.innerWidth < 768;
    };
    checkMobile();
    window.addEventListener('resize', checkMobile);
    
    // Focus the first input if it's empty
    if (items.length === 1 && !items[0].text.trim()) {
      focusInput(0);
    }
    
    return () => window.removeEventListener('resize', checkMobile);
  });
  
  async function focusInput(index: number) {
    await tick();
    const input = document.querySelector(`[data-input-index="${index}"]`) as HTMLInputElement;
    if (input) {
      input.focus();
      if (!input.value.trim()) {
        input.select();
      }
    }
  }
  
  function handleItemsChanged(event: CustomEvent<ChecklistItem[]>) {
    items = event.detail;
    updateData();
  }
  
  function handleAddItem(event: CustomEvent<{ index: number }>) {
    const insertIndex = event.detail.index + 1;
    const newItem: ChecklistItem = { text: '', checked: false };
    items = [
      ...items.slice(0, insertIndex),
      newItem,
      ...items.slice(insertIndex)
    ];
    updateData();
    tick().then(() => focusInput(insertIndex));
  }
  
  function handleRemoveItem(event: CustomEvent<{ index: number }>) {
    const index = event.detail.index;
    if (items.length === 1) {
      // Keep at least one item, just clear it
      items[0] = { text: '', checked: false };
    } else {
      items = items.filter((_, i) => i !== index);
      if (index > 0) {
        tick().then(() => focusInput(index - 1));
      }
    }
    updateData();
  }
  
  function handleUpdateItem(event: CustomEvent<{ index: number; item: ChecklistItem }>) {
    const { index, item } = event.detail;
    items[index] = item;
    updateData();
  }
  
  function addNewItem() {
    const newItem: ChecklistItem = { text: '', checked: false };
    items = [...items, newItem];
    updateData();
    tick().then(() => focusInput(items.length - 1));
  }
  
  function handleGlobalKeyDown(event: KeyboardEvent) {
    // Enter anywhere should add new item if no input is focused
    if (event.key === 'Enter' && document.activeElement?.tagName !== 'INPUT' && document.activeElement?.tagName !== 'SELECT') {
      event.preventDefault();
      addNewItem();
    }
  }
  
  function updateData() {
    dispatch('dataChange', items);
  }
</script>

<svelte:window on:keydown={handleGlobalKeyDown} />

<div class="h-full flex flex-col">
  <!-- Progress Header - Hidden on mobile -->
  {#if !isMobile && (totalCount > 0 || items.some(item => item.text.trim()))}
    <div class="mb-4 p-3 bg-gray-50 rounded-lg">
      <div class="flex items-center justify-between mb-2">
        <span class="text-sm font-medium text-gray-700">
          Progress: {completedCount} of {totalCount} completed
        </span>
        <span class="text-sm text-gray-500">{progressPercentage}%</span>
      </div>
      <div class="w-full bg-gray-200 rounded-full h-2">
        <div 
          class="bg-blue-500 h-2 rounded-full transition-all duration-300"
          style="width: {progressPercentage}%"
        ></div>
      </div>
    </div>
  {/if}

  <!-- Sortable Checklist Items -->
  <div class="flex-1 overflow-y-auto pr-2">
    <SortableChecklist 
      {items}
      {isMobile}
      on:itemsChanged={handleItemsChanged}
      on:addItem={handleAddItem}
      on:removeItem={handleRemoveItem}
      on:updateItem={handleUpdateItem}
    />
  </div>
  
  <!-- Add Item Footer -->
  <div class="mt-6 pt-4 border-t border-gray-200">
    <button 
      on:click={addNewItem}
      class="text-blue-500 hover:text-blue-600 text-sm flex items-center gap-2 p-2 hover:bg-blue-50 rounded-lg transition-colors focus:ring-2 focus:ring-blue-500 focus:bg-blue-50 w-full md:w-auto"
    >
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
      </svg>
      Add new item
      {#if !isMobile}
        <span class="text-gray-400 text-xs ml-2">or press Enter</span>
      {/if}
    </button>
    
    <!-- Keyboard Hints - Hidden on mobile -->
    {#if !isMobile}
      <div class="mt-2 text-xs text-gray-500">
        <div>⌨️ Shortcuts: Enter = new item • Backspace on empty = delete • Drag handle to reorder</div>
      </div>
    {/if}
  </div>
</div>

<style>
  /* Enhanced mobile styles */
  @media (max-width: 767px) {
    :global(.checklist-item) {
      padding: 0.5rem !important;
      gap: 0.5rem !important;
    }
    
    :global(.checklist-item input[type="text"]) {
      font-size: 14px !important;
      padding: 0.25rem 0.5rem !important;
    }
    
    :global(.checklist-item .priority-controls) {
      display: none !important;
    }
  }
</style>

// jotter-react/src/components/editors/ChecklistEditor.tsx
import { useEffect, useRef } from 'react';
import type { ChecklistItem } from '@/lib/types';

type Priority = ChecklistItem['priority'];

function priorityStyle(priority: Priority): React.CSSProperties {
  switch (priority) {
    case 'high':
      return { backgroundColor: '#fee2e2', borderLeft: '4px solid #dc2626' }; // red
    case 'medium':
      return { backgroundColor: '#fef3c7', borderLeft: '4px solid #d97706' }; // amber
    case 'low':
      return { backgroundColor: '#dbeafe', borderLeft: '4px solid #2563eb' }; // blue
    default:
      return {};
  }
}

const EMPTY: ChecklistItem = { text: '', checked: false };

/**
 * Checklist section editor — parity with the Svelte ChecklistEditor/SortableChecklistItem.
 * Progress bar + priority + due dates; Enter adds an item below, Backspace on an empty
 * item deletes it. Date/priority controls hide below md (matching the prod mobile layout).
 * Drag-reorder is deferred to the DnD phase.
 */
export function ChecklistEditor({
  value,
  onChange
}: {
  value: ChecklistItem[];
  onChange: (items: ChecklistItem[]) => void;
}) {
  // Always show at least one (empty) row; an untouched empty list stays [] until edited.
  const items = value.length === 0 ? [EMPTY] : value;
  const pendingFocus = useRef<number | null>(null);

  useEffect(() => {
    if (pendingFocus.current === null) return;
    const i = pendingFocus.current;
    pendingFocus.current = null;
    const el = document.querySelector<HTMLInputElement>(`[data-checklist-input="${i}"]`);
    el?.focus();
  });

  const completed = items.filter((it) => it.checked && it.text.trim()).length;
  const total = items.filter((it) => it.text.trim()).length;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  function commit(next: ChecklistItem[], focusIndex?: number) {
    if (focusIndex !== undefined) pendingFocus.current = focusIndex;
    onChange(next);
  }
  function update(index: number, patch: Partial<ChecklistItem>) {
    commit(items.map((it, j) => (j === index ? { ...it, ...patch } : it)));
  }
  function addAfter(index: number) {
    commit([...items.slice(0, index + 1), { ...EMPTY }, ...items.slice(index + 1)], index + 1);
  }
  function addEnd() {
    commit([...items, { ...EMPTY }], items.length);
  }
  function remove(index: number) {
    if (items.length === 1) {
      commit([{ ...EMPTY }]);
      return;
    }
    commit(
      items.filter((_, j) => j !== index),
      index > 0 ? index - 1 : 0
    );
  }

  // Enter when focus isn't in a field → add an item at the end.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const tag = (document.activeElement?.tagName ?? '').toLowerCase();
      if (e.key === 'Enter' && tag !== 'input' && tag !== 'select' && tag !== 'textarea') {
        e.preventDefault();
        addEnd();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
    // addEnd reads `items` via closure; re-bind when items identity changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [items]);

  return (
    <div className="flex h-full flex-col">
      {total > 0 && (
        <div className="mb-4 hidden rounded-lg bg-slate-50 p-3 md:block">
          <div className="mb-2 flex items-center justify-between">
            <span className="text-sm font-medium text-slate-700">
              Progress: {completed} of {total} completed
            </span>
            <span className="text-sm text-slate-500">{pct}%</span>
          </div>
          <div className="h-2 w-full rounded-full bg-slate-200">
            <div
              className="h-2 rounded-full bg-blue-500 transition-all duration-300"
              style={{ width: `${pct}%` }}
            />
          </div>
        </div>
      )}

      <div className="flex-1 space-y-1 overflow-y-auto pr-1">
        {items.map((item, i) => (
          <div
            key={i}
            className="checklist-item flex items-center gap-2 rounded-lg p-2 md:gap-3 md:p-3"
            style={priorityStyle(item.priority)}
          >
            <input
              type="checkbox"
              checked={item.checked}
              onChange={(e) => update(i, { checked: e.target.checked })}
              className="h-4 w-4 flex-shrink-0 rounded md:h-5 md:w-5"
            />

            {/* Date + priority — hidden below md, matching prod's mobile layout */}
            <input
              type="date"
              value={item.date ?? ''}
              onChange={(e) => update(i, { date: e.target.value || undefined })}
              className="hidden w-32 flex-shrink-0 rounded-lg border border-slate-300 bg-white p-2 text-sm focus:border-blue-500 focus:outline-none md:block"
            />
            <select
              value={item.priority ?? ''}
              onChange={(e) => update(i, { priority: (e.target.value || null) as Priority })}
              className="hidden flex-shrink-0 rounded-lg border border-slate-300 bg-white p-2 text-sm focus:border-blue-500 focus:outline-none md:block"
            >
              <option value="">None</option>
              <option value="low">◦ Low</option>
              <option value="medium">● Medium</option>
              <option value="high">⚡ High</option>
            </select>

            <input
              type="text"
              value={item.text}
              data-checklist-input={i}
              placeholder="Enter task..."
              onChange={(e) => update(i, { text: e.target.value })}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  addAfter(i);
                } else if (e.key === 'Backspace' && !item.text.trim()) {
                  e.preventDefault();
                  remove(i);
                }
              }}
              className="min-w-0 flex-1 rounded-lg border border-slate-300 bg-white p-2 focus:border-blue-500 focus:outline-none"
            />

            <button
              onClick={() => remove(i)}
              title="Remove item"
              aria-label="Remove item"
              className="flex-shrink-0 rounded-lg p-1 text-red-500 transition-colors hover:bg-red-50 hover:text-red-700 md:p-2"
            >
              ✕
            </button>
          </div>
        ))}
      </div>

      <div className="mt-6 border-t border-slate-200 pt-4">
        <button
          onClick={addEnd}
          className="flex w-full items-center gap-2 rounded-lg p-2 text-sm text-blue-500 transition-colors hover:bg-blue-50 hover:text-blue-600 md:w-auto"
        >
          + Add new item
          <span className="ml-2 hidden text-xs text-slate-400 md:inline">or press Enter</span>
        </button>
      </div>
    </div>
  );
}
