// jotter-react/src/components/collections/CollectionCreateCard.tsx
import { useState } from 'react';
import { DEFAULT_COLLECTION_COLORS, LIMITS } from '@/lib/constants';
import type { CollectionSaveInput } from './CollectionCard';

export function CollectionCreateCard({
  count,
  onCreate
}: {
  count: number;
  onCreate: (input: CollectionSaveInput) => void;
}) {
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState('');
  const [color, setColor] = useState<string>('#3B82F6');
  const [description, setDescription] = useState('');

  const atLimit = count >= LIMITS.MAX_COLLECTIONS_PER_USER;

  function reset() {
    setShowForm(false);
    setName('');
    setColor('#3B82F6');
    setDescription('');
  }
  function submit() {
    if (!name.trim()) return;
    onCreate({ name: name.trim(), color, description: description.trim() || undefined });
    reset();
  }
  function onKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      submit();
    } else if (e.key === 'Escape') {
      reset();
    }
  }

  if (showForm) {
    return (
      <div className="rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-5">
        <div className="mb-3 flex items-center gap-3">
          <span
            className="h-4 w-4 flex-shrink-0 rounded-full border border-slate-300"
            style={{ backgroundColor: color }}
          />
          <h3 className="font-semibold text-slate-900">New Collection</h3>
        </div>

        <label className="mb-1 block text-sm font-medium text-slate-700">Name</label>
        <input
          autoFocus
          value={name}
          maxLength={LIMITS.COLLECTION_NAME_MAX_LENGTH}
          onChange={(e) => setName(e.target.value)}
          onKeyDown={onKeyDown}
          placeholder="Collection name"
          className="w-full rounded-md border border-slate-300 px-3 py-2 focus:border-blue-500 focus:outline-none"
        />

        <label className="mt-3 mb-1 block text-sm font-medium text-slate-700">Color</label>
        <div className="flex flex-wrap gap-2">
          {DEFAULT_COLLECTION_COLORS.map((c) => (
            <button
              key={c}
              type="button"
              onClick={() => setColor(c)}
              title={c}
              className={`h-6 w-6 rounded-full border-2 transition hover:scale-110 ${
                color === c ? 'border-slate-800' : 'border-slate-300'
              }`}
              style={{ backgroundColor: c }}
            />
          ))}
        </div>

        <label className="mt-3 mb-1 block text-sm font-medium text-slate-700">
          Description (optional)
        </label>
        <textarea
          value={description}
          maxLength={LIMITS.COLLECTION_DESCRIPTION_MAX_LENGTH}
          onChange={(e) => setDescription(e.target.value)}
          onKeyDown={onKeyDown}
          rows={3}
          placeholder="What will you store in this collection?"
          className="w-full resize-none rounded-md border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
        />

        <div className="mt-3 flex gap-2">
          <button
            onClick={submit}
            disabled={!name.trim()}
            className="rounded-md bg-blue-500 px-4 py-2 text-sm font-medium text-white hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Create Collection
          </button>
          <button
            onClick={reset}
            className="rounded-md bg-slate-200 px-4 py-2 text-sm text-slate-700 hover:bg-slate-300"
          >
            Cancel
          </button>
        </div>
      </div>
    );
  }

  if (atLimit) {
    return (
      <div className="flex min-h-[180px] items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-5 text-center text-sm text-slate-400">
        <div>
          <p className="font-medium text-slate-500">Collection limit reached</p>
          <p className="mt-1 text-xs">
            Maximum of {LIMITS.MAX_COLLECTIONS_PER_USER} collections. Delete one to create a new
            collection.
          </p>
        </div>
      </div>
    );
  }

  return (
    <button
      onClick={() => setShowForm(true)}
      className="group flex min-h-[180px] flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-5 text-center transition hover:border-slate-400 hover:bg-slate-100"
    >
      <span className="mb-2 text-2xl text-slate-400 group-hover:text-slate-600">+</span>
      <span className="font-medium text-slate-600 group-hover:text-slate-800">
        Create New Collection
      </span>
      <span className="mt-1 text-xs text-slate-500">
        Organize your notes into focused collections
      </span>
    </button>
  );
}

// src/lib/components/collections/CollectionCreateCard.svelte
<!-- src/lib/components/collections/CollectionCreateCard.svelte -->
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { LIMITS } from '$lib/constants';

  export let collectionCount: number = 0;

  const dispatch = createEventDispatcher<{
    create: { name: string; color: string; description?: string };
  }>();

  $: isAtLimit = collectionCount >= LIMITS.MAX_COLLECTIONS_PER_USER;

  let showForm: boolean = false;
  let name: string = '';
  let color: string = '#3B82F6';
  let description: string = '';

  const defaultColors = [
    '#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6',
    '#06B6D4', '#F97316', '#84CC16', '#EC4899', '#6B7280'
  ];

  function startCreate() {
    showForm = true;
    name = '';
    color = '#3B82F6';
    description = '';
  }

  function submitCreate() {
    console.log("submitting create event with name, color, description", { name, color, description });
    if (name.trim()) {
      dispatch('create', {
        name: name.trim(),
        color,
        description: description.trim() || undefined
      });
      cancelCreate();
    }
  }

  function cancelCreate() {
    showForm = false;
    name = '';
    color = '#3B82F6';
    description = '';
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      submitCreate();
    } else if (event.key === 'Escape') {
      cancelCreate();
    }
  }
</script>

<div class="group relative p-6 bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg hover:border-gray-400 hover:bg-gray-100 transition-colors min-h-[200px]">
  {#if showForm}
    <!-- Create Form -->
    <div class="space-y-4">
      <!-- Header -->
      <div class="flex items-center space-x-3 mb-4">
        <div 
          class="w-4 h-4 rounded-full border border-gray-300 flex-shrink-0" 
          style="background-color: {color}"
          title="Collection color"
        ></div>
        <h3 class="font-semibold text-gray-900">New Collection</h3>
      </div>

      <!-- Name Input -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">Name</label>
        <input
          type="text"
          bind:value={name}
          on:keydown={handleKeydown}
          placeholder="Collection name"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
          autofocus
        />
      </div>

      <!-- Color Picker -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">Color</label>
        <div class="flex flex-wrap gap-2">
          {#each defaultColors as colorOption}
            <button
              type="button"
              class="w-6 h-6 rounded-full border-2 transition-all hover:scale-110"
              class:border-gray-800={color === colorOption}
              class:border-gray-300={color !== colorOption}
              style="background-color: {colorOption}"
              on:click={() => color = colorOption}
              title="Select {colorOption}"
            ></button>
          {/each}
        </div>
      </div>

      <!-- Description Input -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">Description (optional)</label>
        <textarea
          bind:value={description}
          on:keydown={handleKeydown}
          placeholder="What will you store in this collection?"
          rows="3"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
        ></textarea>
      </div>

      <!-- Action Buttons -->
      <div class="flex items-center space-x-2 pt-2">
        <button
          on:click={submitCreate}
          disabled={!name.trim()}
          class="px-4 py-2 bg-blue-600 text-white text-sm rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium"
        >
          Create Collection
        </button>
        <button
          on:click={cancelCreate}
          class="px-4 py-2 bg-gray-200 text-gray-700 text-sm rounded-md hover:bg-gray-300 transition-colors"
        >
          Cancel
        </button>
      </div>
    </div>
  {:else if isAtLimit}
    <!-- Limit Reached State -->
    <div class="w-full h-full flex items-center justify-center text-center p-4">
      <div class="text-gray-400">
        <!-- Lock Icon -->
        <svg class="w-8 h-8 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
        </svg>

        <span class="text-gray-500 font-medium block">
          Collection Limit Reached
        </span>

        <p class="text-xs text-gray-400 mt-2">
          Maximum of {LIMITS.MAX_COLLECTIONS_PER_USER} collections. Delete one to create a new collection.
        </p>
      </div>
    </div>
  {:else}
    <!-- Create Button -->
    <button
      on:click={startCreate}
      class="w-full h-full flex items-center justify-center text-center focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 rounded-lg"
    >
      <div class="text-gray-400 group-hover:text-gray-600 transition-colors">
        <!-- Plus Icon -->
        <svg class="w-8 h-8 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
        </svg>

        <span class="text-gray-600 group-hover:text-gray-800 font-medium transition-colors block">
          Create New Collection
        </span>

        <p class="text-xs text-gray-500 mt-2 group-hover:text-gray-600 transition-colors">
          Organize your notes into focused collections
        </p>
      </div>
    </button>
  {/if}
</div>
