// jotter-react/src/routes/settings.tsx
import { Link } from '@tanstack/react-router';
import { RequireAuth } from '@/lib/auth/RequireAuth';
import { AppHeader } from '@/components/AppHeader';

export function SettingsRoute() {
  return (
    <RequireAuth>
      <div className="min-h-screen bg-slate-50 text-slate-900">
        <AppHeader>
          <span className="text-slate-300">/</span>
          <span className="text-sm text-slate-600">Settings</span>
        </AppHeader>

        <div className="mx-auto max-w-4xl p-6">
          <h1 className="text-2xl font-bold">Settings</h1>
          <p className="mt-2 text-slate-600">Manage your account and preferences</p>

          <div className="mt-6 rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
            <p className="text-slate-500">User preferences coming soon.</p>
            <Link
              to="/app"
              className="mt-4 inline-block text-sm font-medium text-blue-600 hover:text-blue-800"
            >
              ← Back to Notes
            </Link>
          </div>
        </div>
      </div>
    </RequireAuth>
  );
}

// src/routes/app/settings/+page.svelte
<script lang="ts">
  // User preferences and settings
</script>

<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <div class="mb-8">
    <h1 class="text-2xl font-bold text-gray-900">Settings</h1>
    <p class="text-gray-600 mt-2">Manage your account and preferences</p>
  </div>
  
  <div class="bg-white rounded-lg shadow p-6">
    <p class="text-gray-500">Settings interface coming soon...</p>
    
    <div class="mt-4">
      <a 
        href="/app"
        class="text-blue-600 hover:text-blue-800 text-sm font-medium"
      >
        ← Back to Notes
      </a>
    </div>
  </div>
</div>
