// jotter-react/src/components/layout/UserMenu.tsx
import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { signOut, useAuth } from '@/lib/auth/AuthContext';
import { useDemoMode } from '@/lib/demo/useDemoMode';
import { exitDemoMode } from '@/lib/demo/demoMode';

const GearIcon = () => (
  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
    />
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
    />
  </svg>
);

const CollectionsIcon = () => (
  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
    />
  </svg>
);

const SignOutIcon = () => (
  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
    />
  </svg>
);

export function UserMenu() {
  const { user } = useAuth();
  const demo = useDemoMode();
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onDown = (e: PointerEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('pointerdown', onDown, true);
    return () => document.removeEventListener('pointerdown', onDown, true);
  }, [open]);

  if (demo) {
    return (
      <button
        onClick={() => {
          exitDemoMode(false);
          navigate({ to: '/' });
        }}
        className="rounded-lg bg-blue-500 px-4 py-2 text-sm font-medium text-white hover:bg-blue-600"
      >
        Sign In
      </button>
    );
  }

  const meta = user?.user_metadata ?? {};
  const avatarUrl: string | undefined = meta.avatar_url;
  const fullName: string | undefined = meta.full_name;
  const initial = (fullName?.[0] ?? user?.email?.[0] ?? 'U').toUpperCase();

  async function handleSignOut() {
    try {
      await signOut();
    } catch (e) {
      console.error('Sign out failed:', e);
    }
    navigate({ to: '/' });
  }

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        aria-haspopup="true"
        aria-expanded={open}
        className="flex items-center gap-1.5 rounded-md p-1 hover:bg-slate-100 focus:outline-none"
      >
        {avatarUrl ? (
          <img src={avatarUrl} alt="" className="h-8 w-8 rounded-full" />
        ) : (
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-300 text-sm font-medium text-slate-600">
            {initial}
          </div>
        )}
        <svg
          className={`h-4 w-4 text-slate-400 transition-transform ${open ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {open && (
        <div className="absolute right-0 z-50 mt-2 w-56 rounded-md border border-slate-200 bg-white py-1 shadow-lg">
          <div className="border-b border-slate-100 px-4 py-2 text-sm">
            <div className="font-medium text-slate-700">{fullName ?? 'User'}</div>
            <div className="truncate text-slate-500">{user?.email}</div>
          </div>

          <Link
            to="/app/settings"
            onClick={() => setOpen(false)}
            className="flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50"
          >
            <GearIcon />
            <span>Settings</span>
          </Link>
          <Link
            to="/app"
            onClick={() => setOpen(false)}
            className="flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50"
          >
            <CollectionsIcon />
            <span>Manage Collections</span>
          </Link>

          <hr className="my-1 border-slate-100" />

          <button
            onClick={handleSignOut}
            className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50"
          >
            <SignOutIcon />
            <span>Sign out</span>
          </button>
        </div>
      )}
    </div>
  );
}

// src/lib/components/layout/UserMenu.svelte
<!-- src/lib/components/layout/UserMenu.svelte -->
<script lang="ts">
  import type { User } from '@supabase/supabase-js';
  import { signOut } from '$lib/auth';

  export let user: User | null = null;

  let showUserMenu = false;

  const toggleUserMenu = () => {
    showUserMenu = !showUserMenu;
  };

  const handleSignOut = async () => {
    try {
      await signOut();
    } catch (error) {
      console.error('Sign out failed:', error);
    }
  };

  // Close user menu when clicking outside
  const handleClickOutside = (event: MouseEvent) => {
    const target = event.target as Element;
    if (showUserMenu && !target.closest('.user-menu-container')) {
      showUserMenu = false;
    }
  };

  function getUserInitial(): string {
    if (user?.user_metadata?.full_name) {
      return user.user_metadata.full_name.charAt(0).toUpperCase();
    }
    if (user?.email) {
      return user.email.charAt(0).toUpperCase();
    }
    return 'U';
  }

  function getUserDisplayName(): string {
    return user?.user_metadata?.full_name || 'User';
  }
</script>

<svelte:window on:click={handleClickOutside} />

<div class="relative user-menu-container">
  <button 
    class="flex items-center space-x-2 text-sm text-gray-700 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 rounded-md p-1"
    on:click={toggleUserMenu}
    aria-expanded={showUserMenu}
    aria-haspopup="true"
  >
    {#if user?.user_metadata?.avatar_url}
      <img 
        src={user.user_metadata.avatar_url} 
        alt="User avatar"
        class="w-8 h-8 rounded-full"
      />
    {:else}
      <div class="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center">
        <span class="text-sm text-gray-600 font-medium">
          {getUserInitial()}
        </span>
      </div>
    {/if}
    
    <svg 
      class="w-4 h-4 transition-transform" 
      class:rotate-180={showUserMenu}
      fill="none" 
      stroke="currentColor" 
      viewBox="0 0 24 24"
    >
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
    </svg>
  </button>
  
  {#if showUserMenu}
    <div class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-50 border border-gray-200">
      <!-- User Info -->
      <div class="px-4 py-2 text-sm text-gray-700 border-b border-gray-100">
        <div class="font-medium">{getUserDisplayName()}</div>
        <div class="text-gray-500 truncate">{user?.email}</div>
      </div>
      
      <!-- Menu Items -->
      <a 
        href="/app/settings" 
        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition-colors"
        on:click={() => showUserMenu = false}
      >
        <div class="flex items-center space-x-2">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
          </svg>
          <span>Settings</span>
        </div>
      </a>
      
      <a 
        href="/app" 
        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition-colors"
        on:click={() => showUserMenu = false}
      >
        <div class="flex items-center space-x-2">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
          </svg>
          <span>Manage Collections</span>
        </div>
      </a>
      
      <hr class="my-1" />
      
      <button 
        class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition-colors"
        on:click={handleSignOut}
      >
        <div class="flex items-center space-x-2">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
          </svg>
          <span>Sign out</span>
        </div>
      </button>
    </div>
  {/if}
</div>
